load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "event_data_qualifier",
    srcs = [],
    hdrs = [
        "event_data_qualifier.h",
    ],
    visibility = ["//visibility:public"],
)
