cc_library(
    name = "support",
    testonly = True,
    hdrs = [
        "operators.h",
    ],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
    ],
    visibility = ["//perception:__subpackages__"],
    deps = [
        "//perception/driver/datatype",
    ],
)
