///
/// @file
/// @copyright Copyright (c) 2020. MIT License.
///
#ifndef PERCEPTION_MIDDLEWARE_COMMUNICATION_I_COMMUNICATION_H_
#define PERCEPTION_MIDDLEWARE_COMMUNICATION_I_COMMUNICATION_H_

#endif  /// PERCEPTION_MIDDLEWARE_COMMUNICATION_I_COMMUNICATION_H_
