cc_library(
    name = "datatype",
    srcs = [
        "driver.h",
        "driver_camera_message.h",
        "driver_message.h",
    ],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@nholthaus//:units",
    ],
)
