cc_library(
    name = "datatype",
    hdrs = [
        "camera.h",
    ],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@opencv//:core",
    ],
)
