load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "vehicle_dynamics",
    srcs = ["vehicle_dynamics.cpp"],
    hdrs = ["vehicle_dynamics.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//perception/datatypes",
    ],
)
