cc_library(
    name = "datatype",
    hdrs = [
        "object.h",
    ],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//perception/datatypes",
        "@nholthaus//:units",
    ],
)
