@startuml

class IDetector {
    + {abstract} void Detect(const Image& image)
}

class EyeDetector {
    + void Detect(const Image& image)
    + const FaceTracking& GetFaceTracking() const

    - void UpdateFaceDetection()
    - void UpdateEyeTracking()

    - FaceTracking face_tracking_
}

class HeadDetector {
    + void Detect(const Image& image)
    + const HeadTracking& GetHeadTracking() const

    - HeadTracking head_tracking_
}

class GazeDetector {
    + void Detect(const Image& image)
    + const GazeTracking& GetGazeTracking() const

    - GazeTracking gaze_tracking_
}

class DriverCamera {
    + void IdentifyFacialFeatures()
    + void SetCameraMessage(const CameraMessage& camera_message)
    + const DriverCameraMessage& GetDriverCameraMessage() const

    - void UpdateFaceTracking()
    - void UpdateHeadTracking()
    - void UpdateGazeTracking()

    - FaceDetector face_detector_
    - HeadDetector head_detector_
    - GazeDetector gaze_detector_
}


DriverCamera *.. FaceDetector
DriverCamera *.. EyeDetector
DriverCamera *.. HeadDetector
DriverCamera *.. GazeDetector


IDetector <|-- FaceDetector
IDetector <|-- EyeDetector
IDetector <|-- HeadDetector
IDetector <|-- GazeDetector

@enduml
