cc_library(
    name = "sensor",
    hdrs = [
        "i_sensor.h",
    ],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
    ],
    visibility = ["//visibility:public"],
)
