cc_library(
    name = "support",
    testonly = True,
    srcs = [],
    hdrs = [],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
    ],
    visibility = ["//perception/lifecycle/test:__subpackages__"],
    deps = [
        "//perception/lifecycle/test/support/mocks",
    ],
)
