cc_library(
    name = "lane",
    srcs = ["lane.cpp"],
    hdrs = ["lane.h"],
    features = [
        "treat_warnings_as_errors",
        "strict_warnings",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//perception/datatypes",
        "@opencv",
    ],
)
