cc_library(
    name = "simulation",
    srcs = ["simulation.cpp"],
    hdrs = ["simulation.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//perception/common:logging",
    ],
)
